BINARY_NAME=updateit

all: linux-amd64 windows-amd64 darwin-arm64 darwin-amd64 freebsd-amd64

linux-amd64:
	GOOS=linux GOARCH=amd64 go build -o ${BINARY_NAME}-linux-amd64 .

windows-amd64:
	GOOS=windows GOARCH=amd64 go build -o ${BINARY_NAME}-windows-amd64.exe .

darwin-arm64:
	GOOS=darwin GOARCH=arm64 go build -o ${BINARY_NAME}-darwin-arm64 .

darwin-amd64:
	GOOS=darwin GOARCH=amd64 go build -o ${BINARY_NAME}-darwin-amd64 .

freebsd-amd64:
	GOOS=freebsd GOARCH=amd64 go build -o ${BINARY_NAME}-freebsd-amd64 .

clean:
	rm -f ${BINARY_NAME}-*
	@echo "Cleaned up!"

build: all
	@echo "Successfully built all versions."